# Generated by Django 4.1.4 on 2023-02-03 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('STUDENT', 'STUDENT'), ('TEACHER', 'TEACHER'), ('GRAD', 'GRAD')], default='STUDENT', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('latest_login', models.DateTimeField(auto_now=True)),
                ('isverified', models.BooleanField(default=False)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='infodata',
            fields=[
                ('data_id', models.IntegerField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=120)),
                ('informationdata', models.TextField(blank=True, max_length=10000)),
                ('title', models.CharField(max_length=120)),
                ('tags', models.TextField(max_length=120, null=True)),
                ('views', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('Science', 'Science'), ('Eco', 'Eco'), ('History', 'History'), ('Tech', 'Tech')], max_length=50)),
                ('image', models.ImageField(default='', null=True, upload_to='apiapp/images')),
                ('usertype', models.CharField(default='', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='tasks',
            fields=[
                ('taskid', models.IntegerField(primary_key=True, serialize=False)),
                ('taskname', models.CharField(default='Newtask', max_length=120)),
                ('tskdetail', models.CharField(default='', max_length=50)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
