# Generated by Django 4.1.4 on 2023-02-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='task_topic',
            field=models.CharField(default=None, max_length=25),
        ),
    ]
