# Generated by Django 4.1.4 on 2023-02-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0003_alter_tasks_task_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='task_topic',
            field=models.CharField(default='', max_length=25),
        ),
    ]
